
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The chart of a system or waypoint, which makes the location visible to other agents.
    /// </summary>
    [Serializable]
    public class ChartJsonChartJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypointSymbol")]
        public string? WaypointSymbol { get; set; }
        

        /// <summary>
        /// The agent that submitted the chart for this waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("submittedBy")]
        public string? SubmittedBy { get; set; }
        

        /// <summary>
        /// The time the chart for this waypoint was submitted.
        /// </summary>
        [SerializeField]
        [JsonProperty("submittedOn")]
        public DateTime? SubmittedOn { get; set; }
        
    }
}