
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The details of the required construction materials for a given waypoint under construction.
    /// </summary>
    [Serializable]
    public class ConstructionMaterialJson
    {

        /// <summary>
        /// The good&apos;s symbol.
        /// </summary>
        [SerializeField]
        [JsonProperty("tradeSymbol")]
        public TradeSymbolJsonTradeSymbolJson TradeSymbol { get; set; } = default!;
        

        /// <summary>
        /// The number of units required.
        /// </summary>
        [SerializeField]
        [JsonProperty("required")]
        public long Required { get; set; } = default!;
        

        /// <summary>
        /// The number of units fulfilled toward the required amount.
        /// </summary>
        [SerializeField]
        [JsonProperty("fulfilled")]
        public long Fulfilled { get; set; } = default!;
        
    }
}