
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The construction details of a waypoint.
    /// </summary>
    [Serializable]
    public class ConstructionJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The materials required to construct the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("materials")]
        public List<ConstructionMaterialJson> Materials { get; set; } = default!;
        

        /// <summary>
        /// Whether the waypoint has been constructed.
        /// </summary>
        [SerializeField]
        [JsonProperty("isComplete")]
        public bool IsComplete { get; set; } = default!;
        
    }
}