
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Payments for the contract.
    /// </summary>
    [Serializable]
    public class ContractPaymentJson
    {

        /// <summary>
        /// The amount of credits received up front for accepting the contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("onAccepted")]
        public long OnAccepted { get; set; } = default!;
        

        /// <summary>
        /// The amount of credits received when the contract is fulfilled.
        /// </summary>
        [SerializeField]
        [JsonProperty("onFulfilled")]
        public long OnFulfilled { get; set; } = default!;
        
    }
}