
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The terms to fulfill the contract.
    /// </summary>
    [Serializable]
    public class ContractTermsJson
    {

        /// <summary>
        /// The deadline for the contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("deadline")]
        public DateTime Deadline { get; set; } = default!;
        

        /// <summary>
        /// Payments for the contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("payment")]
        public ContractPaymentJson Payment { get; set; } = default!;
        

        /// <summary>
        /// The cargo that needs to be delivered to fulfill the contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("deliver")]
        public List<ContractDeliverGoodJson>? Deliver { get; set; }
        
    }
}