
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The details of a delivery contract. Includes the type of good, units needed, and the destination.
    /// </summary>
    [Serializable]
    public class ContractDeliverGoodJson
    {

        /// <summary>
        /// The symbol of the trade good to deliver.
        /// </summary>
        [SerializeField]
        [JsonProperty("tradeSymbol")]
        public string TradeSymbol { get; set; } = default!;
        

        /// <summary>
        /// The destination where goods need to be delivered.
        /// </summary>
        [SerializeField]
        [JsonProperty("destinationSymbol")]
        public string DestinationSymbol { get; set; } = default!;
        

        /// <summary>
        /// The number of units that need to be delivered on this contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("unitsRequired")]
        public long UnitsRequired { get; set; } = default!;
        

        /// <summary>
        /// The number of units fulfilled on this contract.
        /// </summary>
        [SerializeField]
        [JsonProperty("unitsFulfilled")]
        public long UnitsFulfilled { get; set; } = default!;
        
    }
}