
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A cooldown is a period of time in which a ship cannot perform certain actions.
    /// </summary>
    [Serializable]
    public class CooldownJson
    {

        /// <summary>
        /// The symbol of the ship that is on cooldown
        /// </summary>
        [SerializeField]
        [JsonProperty("shipSymbol")]
        public string ShipSymbol { get; set; } = default!;
        

        /// <summary>
        /// The total duration of the cooldown in seconds
        /// </summary>
        [SerializeField]
        [JsonProperty("totalSeconds")]
        public long TotalSeconds { get; set; } = default!;
        

        /// <summary>
        /// The remaining duration of the cooldown in seconds
        /// </summary>
        [SerializeField]
        [JsonProperty("remainingSeconds")]
        public long RemainingSeconds { get; set; } = default!;
        

        /// <summary>
        /// The date and time when the cooldown expires in ISO 8601 format
        /// </summary>
        [SerializeField]
        [JsonProperty("expiration")]
        public DateTime? Expiration { get; set; }
        
    }
}