
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Extraction details.
    /// </summary>
    [Serializable]
    public class ExtractionJson
    {

        /// <summary>
        /// Symbol of the ship that executed the extraction.
        /// </summary>
        [SerializeField]
        [JsonProperty("shipSymbol")]
        public string ShipSymbol { get; set; } = default!;
        

        /// <summary>
        /// A yield from the extraction operation.
        /// </summary>
        [SerializeField]
        [JsonProperty("yield")]
        public ExtractionYieldJson Yield { get; set; } = default!;
        
    }
}