
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Faction details.
    /// </summary>
    [Serializable]
    public class FactionJson
    {

        /// <summary>
        /// The symbol of the faction.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public FactionSymbolJsonFactionSymbolJson Symbol { get; set; } = default!;
        

        /// <summary>
        /// Name of the faction.
        /// </summary>
        [SerializeField]
        [JsonProperty("name")]
        public string Name { get; set; } = default!;
        

        /// <summary>
        /// Description of the faction.
        /// </summary>
        [SerializeField]
        [JsonProperty("description")]
        public string Description { get; set; } = default!;
        

        /// <summary>
        /// The waypoint in which the faction&apos;s HQ is located in.
        /// </summary>
        [SerializeField]
        [JsonProperty("headquarters")]
        public string Headquarters { get; set; } = default!;
        

        /// <summary>
        /// List of traits that define this faction.
        /// </summary>
        [SerializeField]
        [JsonProperty("traits")]
        public List<FactionTraitJson> Traits { get; set; } = default!;
        

        /// <summary>
        /// Whether or not the faction is currently recruiting new agents.
        /// </summary>
        [SerializeField]
        [JsonProperty("isRecruiting")]
        public bool IsRecruiting { get; set; } = default!;
        
    }
}