
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class MarketJson
    {

        /// <summary>
        /// The symbol of the market. The symbol is the same as the waypoint where the market is located.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The list of goods that are exported from this market.
        /// </summary>
        [SerializeField]
        [JsonProperty("exports")]
        public List<TradeGoodJson> Exports { get; set; } = default!;
        

        /// <summary>
        /// The list of goods that are sought as imports in this market.
        /// </summary>
        [SerializeField]
        [JsonProperty("imports")]
        public List<TradeGoodJson> Imports { get; set; } = default!;
        

        /// <summary>
        /// The list of goods that are bought and sold between agents at this market.
        /// </summary>
        [SerializeField]
        [JsonProperty("exchange")]
        public List<TradeGoodJson> Exchange { get; set; } = default!;
        

        /// <summary>
        /// The list of recent transactions at this market. Visible only when a ship is present at the market.
        /// </summary>
        [SerializeField]
        [JsonProperty("transactions")]
        public List<MarketTransactionJsonMarketTransactionJson>? Transactions { get; set; }
        

        /// <summary>
        /// The list of goods that are traded at this market. Visible only when a ship is present at the market.
        /// </summary>
        [SerializeField]
        [JsonProperty("tradeGoods")]
        public List<MarketTradeGoodJson>? TradeGoods { get; set; }
        
    }
}