
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class MarketTradeGoodJson
    {

        /// <summary>
        /// The good&apos;s symbol.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public TradeSymbolJsonTradeSymbolJson Symbol { get; set; } = default!;
        

        /// <summary>
        /// The type of trade good (export, import, or exchange).
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public MarketTradeGoodJsonType Type { get; set; } = default!;
        

        /// <summary>
        /// This is the maximum number of units that can be purchased or sold at this market in a single trade for this good. Trade volume also gives an indication of price volatility. A market with a low trade volume will have large price swings, while high trade volume will be more resilient to price changes.
        /// </summary>
        [SerializeField]
        [JsonProperty("tradeVolume")]
        public long TradeVolume { get; set; } = default!;
        

        /// <summary>
        /// The supply level of a trade good.
        /// </summary>
        [SerializeField]
        [JsonProperty("supply")]
        public SupplyLevelJson Supply { get; set; } = default!;
        

        /// <summary>
        /// The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
        /// </summary>
        [SerializeField]
        [JsonProperty("activity")]
        public ActivityLevelJson? Activity { get; set; }
        

        /// <summary>
        /// The price at which this good can be purchased from the market.
        /// </summary>
        [SerializeField]
        [JsonProperty("purchasePrice")]
        public long PurchasePrice { get; set; } = default!;
        

        /// <summary>
        /// The price at which this good can be sold to the market.
        /// </summary>
        [SerializeField]
        [JsonProperty("sellPrice")]
        public long SellPrice { get; set; } = default!;
        
    }
}