
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Meta details for pagination.
    /// </summary>
    [Serializable]
    public class MetaJson
    {

        /// <summary>
        /// Shows the total amount of items of this kind that exist.
        /// </summary>
        [SerializeField]
        [JsonProperty("total")]
        public long Total { get; set; } = default!;
        

        /// <summary>
        /// A page denotes an amount of items, offset from the first item. Each page holds an amount of items equal to the `limit`.
        /// </summary>
        [SerializeField]
        [JsonProperty("page")]
        public long Page { get; set; } = default!;
        

        /// <summary>
        /// The amount of items in each page. Limits how many items can be fetched at once.
        /// </summary>
        [SerializeField]
        [JsonProperty("limit")]
        public long Limit { get; set; } = default!;
        
    }
}