
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A waypoint that was scanned by a ship.
    /// </summary>
    [Serializable]
    public class ScannedWaypointJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The type of waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public WaypointTypeJsonWaypointTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("systemSymbol")]
        public string SystemSymbol { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the x axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the y axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        

        /// <summary>
        /// List of waypoints that orbit this waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("orbitals")]
        public List<WaypointOrbitalJson> Orbitals { get; set; } = default!;
        

        /// <summary>
        /// The faction that controls the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("faction")]
        public WaypointFactionJson? Faction { get; set; }
        

        /// <summary>
        /// The traits of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("traits")]
        public List<WaypointTraitJson> Traits { get; set; } = default!;
        

        /// <summary>
        /// The chart of a system or waypoint, which makes the location visible to other agents.
        /// </summary>
        [SerializeField]
        [JsonProperty("chart")]
        public ChartJsonChartJson? Chart { get; set; }
        
    }
}