
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Details of a system was that scanned.
    /// </summary>
    [Serializable]
    public class ScannedSystemJson
    {

        /// <summary>
        /// Symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// Symbol of the system&apos;s sector.
        /// </summary>
        [SerializeField]
        [JsonProperty("sectorSymbol")]
        public string SectorSymbol { get; set; } = default!;
        

        /// <summary>
        /// The type of system.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public SystemTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the x axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the y axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        

        /// <summary>
        /// The system&apos;s distance from the scanning ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("distance")]
        public long Distance { get; set; } = default!;
        
    }
}