
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The ship that was scanned. Details include information about the ship that could be detected by the scanner.
    /// </summary>
    [Serializable]
    public class ScannedShipJson
    {

        /// <summary>
        /// The globally unique identifier of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The public registration information of the ship
        /// </summary>
        [SerializeField]
        [JsonProperty("registration")]
        public ShipRegistrationJson Registration { get; set; } = default!;
        

        /// <summary>
        /// The navigation information of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("nav")]
        public ShipNavJsonShipNavJson Nav { get; set; } = default!;
        

        /// <summary>
        /// The frame of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("frame")]
        public Frame? Frame { get; set; }
        

        /// <summary>
        /// The reactor of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("reactor")]
        public Reactor? Reactor { get; set; }
        

        /// <summary>
        /// The engine of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("engine")]
        public Engine Engine { get; set; } = default!;
        

        /// <summary>
        /// List of mounts installed in the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("mounts")]
        public List<Mounts>? Mounts { get; set; }
        
    }
}