
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Result of a scrap transaction.
    /// </summary>
    [Serializable]
    public class ScrapTransactionJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypointSymbol")]
        public string WaypointSymbol { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("shipSymbol")]
        public string ShipSymbol { get; set; } = default!;
        

        /// <summary>
        /// The total price of the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("totalPrice")]
        public long TotalPrice { get; set; } = default!;
        

        /// <summary>
        /// The timestamp of the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = default!;
        
    }
}