
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The symbol of the engine.
    /// </summary>
    public enum ShipEngineJsonSymbol
    {
        [JsonProperty("ENGINE_IMPULSE_DRIVE_I")]
        EngineImpulseDriveI,
        [JsonProperty("ENGINE_ION_DRIVE_I")]
        EngineIonDriveI,
        [JsonProperty("ENGINE_ION_DRIVE_II")]
        EngineIonDriveIi,
        [JsonProperty("ENGINE_HYPER_DRIVE_I")]
        EngineHyperDriveI,
    }

    public static class ShipEngineJsonSymbolExtension
    {
        public static string Value(this ShipEngineJsonSymbol value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ShipEngineJsonSymbol ToEnum(this string value)
        {
            foreach(var field in typeof(ShipEngineJsonSymbol).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (ShipEngineJsonSymbol)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum ShipEngineJsonSymbol");
        }
    }

}