
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ShipTypes
    {

        /// <summary>
        /// Type of ship
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public ShipTypeJsonShipTypeJson Type { get; set; } = default!;
        
    }
}