
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The routing information for the ship&apos;s most recent transit or current location.
    /// </summary>
    [Serializable]
    public class ShipNavRouteJson
    {

        /// <summary>
        /// The destination or departure of a ships nav route.
        /// </summary>
        [SerializeField]
        [JsonProperty("destination")]
        public ShipNavRouteWaypointJson Destination { get; set; } = default!;
        

        /// <summary>
        /// The destination or departure of a ships nav route.
        /// </summary>
        [SerializeField]
        [JsonProperty("origin")]
        public ShipNavRouteWaypointJson Origin { get; set; } = default!;
        

        /// <summary>
        /// The date time of the ship&apos;s departure.
        /// </summary>
        [SerializeField]
        [JsonProperty("departureTime")]
        public DateTime DepartureTime { get; set; } = default!;
        

        /// <summary>
        /// The date time of the ship&apos;s arrival. If the ship is in-transit, this is the expected time of arrival.
        /// </summary>
        [SerializeField]
        [JsonProperty("arrival")]
        public DateTime Arrival { get; set; } = default!;
        
    }
}