
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Ship cargo details.
    /// </summary>
    [Serializable]
    public class ShipCargoJson
    {

        /// <summary>
        /// The max number of items that can be stored in the cargo hold.
        /// </summary>
        [SerializeField]
        [JsonProperty("capacity")]
        public long Capacity { get; set; } = default!;
        

        /// <summary>
        /// The number of items currently stored in the cargo hold.
        /// </summary>
        [SerializeField]
        [JsonProperty("units")]
        public long Units { get; set; } = default!;
        

        /// <summary>
        /// The items currently in the cargo hold.
        /// </summary>
        [SerializeField]
        [JsonProperty("inventory")]
        public List<ShipCargoItemJson> Inventory { get; set; } = default!;
        
    }
}