
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The navigation information of the ship.
    /// </summary>
    [Serializable]
    public class ShipNavJson
    {

        /// <summary>
        /// The symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("systemSymbol")]
        public string SystemSymbol { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypointSymbol")]
        public string WaypointSymbol { get; set; } = default!;
        

        /// <summary>
        /// The routing information for the ship&apos;s most recent transit or current location.
        /// </summary>
        [SerializeField]
        [JsonProperty("route")]
        public ShipNavRouteJson Route { get; set; } = default!;
        

        /// <summary>
        /// The current status of the ship
        /// </summary>
        [SerializeField]
        [JsonProperty("status")]
        public ShipNavStatusJson Status { get; set; } = default!;
        

        /// <summary>
        /// The ship&apos;s set speed when traveling between waypoints or systems.
        /// </summary>
        [SerializeField]
        [JsonProperty("flightMode")]
        public ShipNavFlightModeJsonShipNavFlightModeJson FlightMode { get; set; } = default!;
        
    }
}