
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The destination or departure of a ships nav route.
    /// </summary>
    [Serializable]
    public class ShipNavRouteWaypointJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The type of waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public WaypointTypeJsonWaypointTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("systemSymbol")]
        public string SystemSymbol { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the x axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Position in the universe in the y axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        
    }
}