
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The public registration information of the ship
    /// </summary>
    [Serializable]
    public class ShipRegistrationJson
    {

        /// <summary>
        /// The agent&apos;s registered name of the ship
        /// </summary>
        [SerializeField]
        [JsonProperty("name")]
        public string Name { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the faction the ship is registered with
        /// </summary>
        [SerializeField]
        [JsonProperty("factionSymbol")]
        public string FactionSymbol { get; set; } = default!;
        

        /// <summary>
        /// The registered role of the ship
        /// </summary>
        [SerializeField]
        [JsonProperty("role")]
        public ShipRoleJson Role { get; set; } = default!;
        
    }
}