
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The requirements for installation on a ship
    /// </summary>
    [Serializable]
    public class ShipRequirementsJson
    {

        /// <summary>
        /// The amount of power required from the reactor.
        /// </summary>
        [SerializeField]
        [JsonProperty("power")]
        public long? Power { get; set; }
        

        /// <summary>
        /// The number of crew required for operation.
        /// </summary>
        [SerializeField]
        [JsonProperty("crew")]
        public long? Crew { get; set; }
        

        /// <summary>
        /// The number of module slots required for installation.
        /// </summary>
        [SerializeField]
        [JsonProperty("slots")]
        public long? Slots { get; set; }
        
    }
}