
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Details of the ship&apos;s fuel tanks including how much fuel was consumed during the last transit or action.
    /// </summary>
    [Serializable]
    public class ShipFuelJson
    {

        /// <summary>
        /// The current amount of fuel in the ship&apos;s tanks.
        /// </summary>
        [SerializeField]
        [JsonProperty("current")]
        public long Current { get; set; } = default!;
        

        /// <summary>
        /// The maximum amount of fuel the ship&apos;s tanks can hold.
        /// </summary>
        [SerializeField]
        [JsonProperty("capacity")]
        public long Capacity { get; set; } = default!;
        

        /// <summary>
        /// An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.
        /// </summary>
        [SerializeField]
        [JsonProperty("consumed")]
        public ShipFuelJsonConsumed? Consumed { get; set; }
        
    }
}