
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The current status of the ship
    /// </summary>
    public enum ShipNavStatusJson
    {
        [JsonProperty("IN_TRANSIT")]
        InTransit,
        [JsonProperty("IN_ORBIT")]
        InOrbit,
        [JsonProperty("DOCKED")]
        Docked,
    }

    public static class ShipNavStatusJsonExtension
    {
        public static string Value(this ShipNavStatusJson value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ShipNavStatusJson ToEnum(this string value)
        {
            foreach(var field in typeof(ShipNavStatusJson).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (ShipNavStatusJson)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum ShipNavStatusJson");
        }
    }

}