
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ShipyardJson
    {

        /// <summary>
        /// The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The list of ship types available for purchase at this shipyard.
        /// </summary>
        [SerializeField]
        [JsonProperty("shipTypes")]
        public List<ShipTypes> ShipTypes { get; set; } = default!;
        

        /// <summary>
        /// The list of recent transactions at this shipyard.
        /// </summary>
        [SerializeField]
        [JsonProperty("transactions")]
        public List<ShipyardTransactionJsonShipyardTransactionJson>? Transactions { get; set; }
        

        /// <summary>
        /// The ships that are currently available for purchase at the shipyard.
        /// </summary>
        [SerializeField]
        [JsonProperty("ships")]
        public List<ShipyardShipJson>? Ships { get; set; }
        

        /// <summary>
        /// The fee to modify a ship at this shipyard. This includes installing or removing modules and mounts on a ship. In the case of mounts, the fee is a flat rate per mount. In the case of modules, the fee is per slot the module occupies.
        /// </summary>
        [SerializeField]
        [JsonProperty("modificationsFee")]
        public long ModificationsFee { get; set; } = default!;
        
    }
}