
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Ship details.
    /// </summary>
    [Serializable]
    public class ShipJson
    {

        /// <summary>
        /// The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The public registration information of the ship
        /// </summary>
        [SerializeField]
        [JsonProperty("registration")]
        public ShipRegistrationJson Registration { get; set; } = default!;
        

        /// <summary>
        /// The navigation information of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("nav")]
        public ShipNavJsonShipNavJson Nav { get; set; } = default!;
        

        /// <summary>
        /// The ship&apos;s crew service and maintain the ship&apos;s systems and equipment.
        /// </summary>
        [SerializeField]
        [JsonProperty("crew")]
        public ShipCrewJson Crew { get; set; } = default!;
        

        /// <summary>
        /// The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
        /// </summary>
        [SerializeField]
        [JsonProperty("frame")]
        public ShipFrameJson Frame { get; set; } = default!;
        

        /// <summary>
        /// The reactor of the ship. The reactor is responsible for powering the ship&apos;s systems and weapons.
        /// </summary>
        [SerializeField]
        [JsonProperty("reactor")]
        public ShipReactorJson Reactor { get; set; } = default!;
        

        /// <summary>
        /// The engine determines how quickly a ship travels between waypoints.
        /// </summary>
        [SerializeField]
        [JsonProperty("engine")]
        public ShipEngineJson Engine { get; set; } = default!;
        

        /// <summary>
        /// A cooldown is a period of time in which a ship cannot perform certain actions.
        /// </summary>
        [SerializeField]
        [JsonProperty("cooldown")]
        public CooldownJsonCooldownJson Cooldown { get; set; } = default!;
        

        /// <summary>
        /// Modules installed in this ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("modules")]
        public List<ShipModuleJson> Modules { get; set; } = default!;
        

        /// <summary>
        /// Mounts installed in this ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("mounts")]
        public List<ShipMountJsonShipMountJson> Mounts { get; set; } = default!;
        

        /// <summary>
        /// Ship cargo details.
        /// </summary>
        [SerializeField]
        [JsonProperty("cargo")]
        public ShipCargoJsonShipCargoJson Cargo { get; set; } = default!;
        

        /// <summary>
        /// Details of the ship&apos;s fuel tanks including how much fuel was consumed during the last transit or action.
        /// </summary>
        [SerializeField]
        [JsonProperty("fuel")]
        public ShipFuelJsonShipFuelJson Fuel { get; set; } = default!;
        
    }
}