
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Symbol of the reactor.
    /// </summary>
    public enum ShipReactorJsonSymbol
    {
        [JsonProperty("REACTOR_SOLAR_I")]
        ReactorSolarI,
        [JsonProperty("REACTOR_FUSION_I")]
        ReactorFusionI,
        [JsonProperty("REACTOR_FISSION_I")]
        ReactorFissionI,
        [JsonProperty("REACTOR_CHEMICAL_I")]
        ReactorChemicalI,
        [JsonProperty("REACTOR_ANTIMATTER_I")]
        ReactorAntimatterI,
    }

    public static class ShipReactorJsonSymbolExtension
    {
        public static string Value(this ShipReactorJsonSymbol value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ShipReactorJsonSymbol ToEnum(this string value)
        {
            foreach(var field in typeof(ShipReactorJsonSymbol).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (ShipReactorJsonSymbol)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum ShipReactorJsonSymbol");
        }
    }

}