
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Results of a transaction with a shipyard.
    /// </summary>
    [Serializable]
    public class ShipyardTransactionJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypointSymbol")]
        public string WaypointSymbol { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the ship that was the subject of the transaction.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [SerializeField]
        [JsonProperty("shipSymbol")]
        public string ShipSymbol { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the ship that was the subject of the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("shipType")]
        public string ShipType { get; set; } = default!;
        

        /// <summary>
        /// The price of the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("price")]
        public long Price { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the agent that made the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("agentSymbol")]
        public string AgentSymbol { get; set; } = default!;
        

        /// <summary>
        /// The timestamp of the transaction.
        /// </summary>
        [SerializeField]
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = default!;
        
    }
}