
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A yield from the siphon operation.
    /// </summary>
    [Serializable]
    public class SiphonYieldJson
    {

        /// <summary>
        /// The good&apos;s symbol.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public TradeSymbolJsonTradeSymbolJson Symbol { get; set; } = default!;
        

        /// <summary>
        /// The number of units siphoned that were placed into the ship&apos;s cargo hold.
        /// </summary>
        [SerializeField]
        [JsonProperty("units")]
        public long Units { get; set; } = default!;
        
    }
}