
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
    /// </summary>
    public enum Size
    {
        [JsonProperty("SMALL")]
        Small,
        [JsonProperty("MODERATE")]
        Moderate,
        [JsonProperty("LARGE")]
        Large,
    }

    public static class SizeExtension
    {
        public static string Value(this Size value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Size ToEnum(this string value)
        {
            foreach(var field in typeof(Size).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (Size)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum Size");
        }
    }

}