
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
    /// </summary>
    [Serializable]
    public class SurveyJson
    {

        /// <summary>
        /// A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
        /// </summary>
        [SerializeField]
        [JsonProperty("signature")]
        public string Signature { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the waypoint that this survey is for.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.
        /// </summary>
        [SerializeField]
        [JsonProperty("deposits")]
        public List<SurveyDepositJson> Deposits { get; set; } = default!;
        

        /// <summary>
        /// The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
        /// </summary>
        [SerializeField]
        [JsonProperty("expiration")]
        public DateTime Expiration { get; set; } = default!;
        

        /// <summary>
        /// The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
        /// </summary>
        [SerializeField]
        [JsonProperty("size")]
        public Size Size { get; set; } = default!;
        
    }
}