
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class SystemWaypointJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The type of waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public WaypointTypeJsonWaypointTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the waypoint on the system&apos;s x axis. This is not an absolute position in the universe.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the waypoint on the system&apos;s y axis. This is not an absolute position in the universe.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        

        /// <summary>
        /// Waypoints that orbit this waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("orbitals")]
        public List<WaypointOrbitalJson> Orbitals { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
        /// </summary>
        [SerializeField]
        [JsonProperty("orbits")]
        public string? Orbits { get; set; }
        
    }
}