
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The type of system.
    /// </summary>
    public enum SystemTypeJson
    {
        [JsonProperty("NEUTRON_STAR")]
        NeutronStar,
        [JsonProperty("RED_STAR")]
        RedStar,
        [JsonProperty("ORANGE_STAR")]
        OrangeStar,
        [JsonProperty("BLUE_STAR")]
        BlueStar,
        [JsonProperty("YOUNG_STAR")]
        YoungStar,
        [JsonProperty("WHITE_DWARF")]
        WhiteDwarf,
        [JsonProperty("BLACK_HOLE")]
        BlackHole,
        [JsonProperty("HYPERGIANT")]
        Hypergiant,
        [JsonProperty("NEBULA")]
        Nebula,
        [JsonProperty("UNSTABLE")]
        Unstable,
    }

    public static class SystemTypeJsonExtension
    {
        public static string Value(this SystemTypeJson value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SystemTypeJson ToEnum(this string value)
        {
            foreach(var field in typeof(SystemTypeJson).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (SystemTypeJson)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum SystemTypeJson");
        }
    }

}