
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class SystemJson
    {

        /// <summary>
        /// The symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the sector.
        /// </summary>
        [SerializeField]
        [JsonProperty("sectorSymbol")]
        public string SectorSymbol { get; set; } = default!;
        

        /// <summary>
        /// The type of system.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public SystemTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the system in the sector in the x axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the system in the sector in the y axis.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        

        /// <summary>
        /// Waypoints in this system.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypoints")]
        public List<SystemWaypointJson> Waypoints { get; set; } = default!;
        

        /// <summary>
        /// Factions that control this system.
        /// </summary>
        [SerializeField]
        [JsonProperty("factions")]
        public List<SystemFactionJson> Factions { get; set; } = default!;
        
    }
}