
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The unique identifier of the trait.
    /// </summary>
    public enum WaypointTraitSymbolJson
    {
        [JsonProperty("UNCHARTED")]
        Uncharted,
        [JsonProperty("UNDER_CONSTRUCTION")]
        UnderConstruction,
        [JsonProperty("MARKETPLACE")]
        Marketplace,
        [JsonProperty("SHIPYARD")]
        Shipyard,
        [JsonProperty("OUTPOST")]
        Outpost,
        [JsonProperty("SCATTERED_SETTLEMENTS")]
        ScatteredSettlements,
        [JsonProperty("SPRAWLING_CITIES")]
        SprawlingCities,
        [JsonProperty("MEGA_STRUCTURES")]
        MegaStructures,
        [JsonProperty("PIRATE_BASE")]
        PirateBase,
        [JsonProperty("OVERCROWDED")]
        Overcrowded,
        [JsonProperty("HIGH_TECH")]
        HighTech,
        [JsonProperty("CORRUPT")]
        Corrupt,
        [JsonProperty("BUREAUCRATIC")]
        Bureaucratic,
        [JsonProperty("TRADING_HUB")]
        TradingHub,
        [JsonProperty("INDUSTRIAL")]
        Industrial,
        [JsonProperty("BLACK_MARKET")]
        BlackMarket,
        [JsonProperty("RESEARCH_FACILITY")]
        ResearchFacility,
        [JsonProperty("MILITARY_BASE")]
        MilitaryBase,
        [JsonProperty("SURVEILLANCE_OUTPOST")]
        SurveillanceOutpost,
        [JsonProperty("EXPLORATION_OUTPOST")]
        ExplorationOutpost,
        [JsonProperty("MINERAL_DEPOSITS")]
        MineralDeposits,
        [JsonProperty("COMMON_METAL_DEPOSITS")]
        CommonMetalDeposits,
        [JsonProperty("PRECIOUS_METAL_DEPOSITS")]
        PreciousMetalDeposits,
        [JsonProperty("RARE_METAL_DEPOSITS")]
        RareMetalDeposits,
        [JsonProperty("METHANE_POOLS")]
        MethanePools,
        [JsonProperty("ICE_CRYSTALS")]
        IceCrystals,
        [JsonProperty("EXPLOSIVE_GASES")]
        ExplosiveGases,
        [JsonProperty("STRONG_MAGNETOSPHERE")]
        StrongMagnetosphere,
        [JsonProperty("VIBRANT_AURORAS")]
        VibrantAuroras,
        [JsonProperty("SALT_FLATS")]
        SaltFlats,
        [JsonProperty("CANYONS")]
        Canyons,
        [JsonProperty("PERPETUAL_DAYLIGHT")]
        PerpetualDaylight,
        [JsonProperty("PERPETUAL_OVERCAST")]
        PerpetualOvercast,
        [JsonProperty("DRY_SEABEDS")]
        DrySeabeds,
        [JsonProperty("MAGMA_SEAS")]
        MagmaSeas,
        [JsonProperty("SUPERVOLCANOES")]
        Supervolcanoes,
        [JsonProperty("ASH_CLOUDS")]
        AshClouds,
        [JsonProperty("VAST_RUINS")]
        VastRuins,
        [JsonProperty("MUTATED_FLORA")]
        MutatedFlora,
        [JsonProperty("TERRAFORMED")]
        Terraformed,
        [JsonProperty("EXTREME_TEMPERATURES")]
        ExtremeTemperatures,
        [JsonProperty("EXTREME_PRESSURE")]
        ExtremePressure,
        [JsonProperty("DIVERSE_LIFE")]
        DiverseLife,
        [JsonProperty("SCARCE_LIFE")]
        ScarceLife,
        [JsonProperty("FOSSILS")]
        Fossils,
        [JsonProperty("WEAK_GRAVITY")]
        WeakGravity,
        [JsonProperty("STRONG_GRAVITY")]
        StrongGravity,
        [JsonProperty("CRUSHING_GRAVITY")]
        CrushingGravity,
        [JsonProperty("TOXIC_ATMOSPHERE")]
        ToxicAtmosphere,
        [JsonProperty("CORROSIVE_ATMOSPHERE")]
        CorrosiveAtmosphere,
        [JsonProperty("BREATHABLE_ATMOSPHERE")]
        BreathableAtmosphere,
        [JsonProperty("THIN_ATMOSPHERE")]
        ThinAtmosphere,
        [JsonProperty("JOVIAN")]
        Jovian,
        [JsonProperty("ROCKY")]
        Rocky,
        [JsonProperty("VOLCANIC")]
        Volcanic,
        [JsonProperty("FROZEN")]
        Frozen,
        [JsonProperty("SWAMP")]
        Swamp,
        [JsonProperty("BARREN")]
        Barren,
        [JsonProperty("TEMPERATE")]
        Temperate,
        [JsonProperty("JUNGLE")]
        Jungle,
        [JsonProperty("OCEAN")]
        Ocean,
        [JsonProperty("RADIOACTIVE")]
        Radioactive,
        [JsonProperty("MICRO_GRAVITY_ANOMALIES")]
        MicroGravityAnomalies,
        [JsonProperty("DEBRIS_CLUSTER")]
        DebrisCluster,
        [JsonProperty("DEEP_CRATERS")]
        DeepCraters,
        [JsonProperty("SHALLOW_CRATERS")]
        ShallowCraters,
        [JsonProperty("UNSTABLE_COMPOSITION")]
        UnstableComposition,
        [JsonProperty("HOLLOWED_INTERIOR")]
        HollowedInterior,
        [JsonProperty("STRIPPED")]
        Stripped,
    }

    public static class WaypointTraitSymbolJsonExtension
    {
        public static string Value(this WaypointTraitSymbolJson value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static WaypointTraitSymbolJson ToEnum(this string value)
        {
            foreach(var field in typeof(WaypointTraitSymbolJson).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (WaypointTraitSymbolJson)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum WaypointTraitSymbolJson");
        }
    }

}