
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
    /// </summary>
    [Serializable]
    public class WaypointJson
    {

        /// <summary>
        /// The symbol of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// The type of waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("type")]
        public WaypointTypeJsonWaypointTypeJson Type { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the system.
        /// </summary>
        [SerializeField]
        [JsonProperty("systemSymbol")]
        public string SystemSymbol { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the waypoint on the system&apos;s x axis. This is not an absolute position in the universe.
        /// </summary>
        [SerializeField]
        [JsonProperty("x")]
        public long X { get; set; } = default!;
        

        /// <summary>
        /// Relative position of the waypoint on the system&apos;s y axis. This is not an absolute position in the universe.
        /// </summary>
        [SerializeField]
        [JsonProperty("y")]
        public long Y { get; set; } = default!;
        

        /// <summary>
        /// Waypoints that orbit this waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("orbitals")]
        public List<WaypointOrbitalJson> Orbitals { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
        /// </summary>
        [SerializeField]
        [JsonProperty("orbits")]
        public string? Orbits { get; set; }
        

        /// <summary>
        /// The faction that controls the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("faction")]
        public WaypointFactionJson? Faction { get; set; }
        

        /// <summary>
        /// The traits of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("traits")]
        public List<WaypointTraitJson> Traits { get; set; } = default!;
        

        /// <summary>
        /// The modifiers of the waypoint.
        /// </summary>
        [SerializeField]
        [JsonProperty("modifiers")]
        public List<WaypointModifierJson>? Modifiers { get; set; }
        

        /// <summary>
        /// The chart of a system or waypoint, which makes the location visible to other agents.
        /// </summary>
        [SerializeField]
        [JsonProperty("chart")]
        public ChartJsonChartJson? Chart { get; set; }
        

        /// <summary>
        /// True if the waypoint is under construction.
        /// </summary>
        [SerializeField]
        [JsonProperty("isUnderConstruction")]
        public bool IsUnderConstruction { get; set; } = default!;
        
    }
}