
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class CreateShipSystemScanData
    {

        /// <summary>
        /// A cooldown is a period of time in which a ship cannot perform certain actions.
        /// </summary>
        [SerializeField]
        [JsonProperty("cooldown")]
        public CooldownJson Cooldown { get; set; } = default!;
        

        /// <summary>
        /// List of scanned systems.
        /// </summary>
        [SerializeField]
        [JsonProperty("systems")]
        public List<ScannedSystemJson> Systems { get; set; } = default!;
        
    }
}