
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ExtractResourcesRequestBody
    {

        /// <summary>
        /// A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
        /// </summary>
        [SerializeField]
        [JsonProperty("survey")]
        public SurveyJson? Survey { get; set; }
        
    }
}