
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Fetched status successfully.
    /// </summary>
    [Serializable]
    public class GetStatusResponseBody
    {

        /// <summary>
        /// The current status of the game server.
        /// </summary>
        [SerializeField]
        [JsonProperty("status")]
        public string Status { get; set; } = default!;
        

        /// <summary>
        /// The current version of the API.
        /// </summary>
        [SerializeField]
        [JsonProperty("version")]
        public string Version { get; set; } = default!;
        

        /// <summary>
        /// The date when the game server was last reset.
        /// </summary>
        [SerializeField]
        [JsonProperty("resetDate")]
        public string ResetDate { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("description")]
        public string Description { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("stats")]
        public Stats Stats { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("leaderboards")]
        public Leaderboards Leaderboards { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("serverResets")]
        public ServerResets ServerResets { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("announcements")]
        public List<Announcements> Announcements { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("links")]
        public List<Links> Links { get; set; } = default!;
        
    }
}