
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Successfully fetched waypoint.
    /// </summary>
    [Serializable]
    public class GetWaypointResponseBody
    {

        /// <summary>
        /// A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
        /// </summary>
        [SerializeField]
        [JsonProperty("data")]
        public WaypointJson Data { get; set; } = default!;
        
    }
}