
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class JumpShipData
    {

        /// <summary>
        /// The navigation information of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("nav")]
        public ShipNavJson Nav { get; set; } = default!;
        

        /// <summary>
        /// A cooldown is a period of time in which a ship cannot perform certain actions.
        /// </summary>
        [SerializeField]
        [JsonProperty("cooldown")]
        public CooldownJson Cooldown { get; set; } = default!;
        

        /// <summary>
        /// Result of a transaction with a market.
        /// </summary>
        [SerializeField]
        [JsonProperty("transaction")]
        public MarketTransactionJson Transaction { get; set; } = default!;
        

        /// <summary>
        /// Agent details.
        /// </summary>
        [SerializeField]
        [JsonProperty("agent")]
        public AgentJson Agent { get; set; } = default!;
        
    }
}