
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The type of good to produce out of the refining process.
    /// </summary>
    public enum Produce
    {
        [JsonProperty("IRON")]
        Iron,
        [JsonProperty("COPPER")]
        Copper,
        [JsonProperty("SILVER")]
        Silver,
        [JsonProperty("GOLD")]
        Gold,
        [JsonProperty("ALUMINUM")]
        Aluminum,
        [JsonProperty("PLATINUM")]
        Platinum,
        [JsonProperty("URANITE")]
        Uranite,
        [JsonProperty("MERITIUM")]
        Meritium,
        [JsonProperty("FUEL")]
        Fuel,
    }

    public static class ProduceExtension
    {
        public static string Value(this Produce value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Produce ToEnum(this string value)
        {
            foreach(var field in typeof(Produce).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (Produce)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum Produce");
        }
    }

}