
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class PurchaseShipRequestBody
    {

        /// <summary>
        /// Type of ship
        /// </summary>
        [SerializeField]
        [JsonProperty("shipType")]
        public ShipTypeJson ShipType { get; set; } = default!;
        

        /// <summary>
        /// The symbol of the waypoint you want to purchase the ship at.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypointSymbol")]
        public string WaypointSymbol { get; set; } = default!;
        
    }
}