
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Purchased goods successfully.
    /// </summary>
    [Serializable]
    public class PurchaseCargoPurchaseCargo201Response
    {

        [SerializeField]
        [JsonProperty("data")]
        public PurchaseCargoData Data { get; set; } = default!;
        
    }
}