
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class PurchaseShipData
    {

        /// <summary>
        /// Agent details.
        /// </summary>
        [SerializeField]
        [JsonProperty("agent")]
        public AgentJson Agent { get; set; } = default!;
        

        /// <summary>
        /// Ship details.
        /// </summary>
        [SerializeField]
        [JsonProperty("ship")]
        public ShipJson Ship { get; set; } = default!;
        

        /// <summary>
        /// Results of a transaction with a shipyard.
        /// </summary>
        [SerializeField]
        [JsonProperty("transaction")]
        public ShipyardTransactionJson Transaction { get; set; } = default!;
        
    }
}