
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class RefuelShipRequestBody
    {

        /// <summary>
        /// The amount of fuel to fill in the ship&apos;s tanks. When not specified, the ship will be refueled to its maximum fuel capacity. If the amount specified is greater than the ship&apos;s remaining capacity, the ship will only be refueled to its maximum fuel capacity. The amount specified is not in market units but in ship fuel units.
        /// </summary>
        [SerializeField]
        [JsonProperty("units")]
        public long? Units { get; set; }
        

        /// <summary>
        /// Wether to use the FUEL thats in your cargo or not. Default: false
        /// </summary>
        [SerializeField]
        [JsonProperty("fromCargo")]
        public bool? FromCargo { get; set; }
        
    }
}