
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class RegisterRequestBody
    {

        /// <summary>
        /// The symbol of the faction.
        /// </summary>
        [SerializeField]
        [JsonProperty("faction")]
        public FactionSymbolJson Faction { get; set; } = default!;
        

        /// <summary>
        /// Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = default!;
        

        /// <summary>
        /// Your email address. This is used if you reserved your call sign between resets.
        /// </summary>
        [SerializeField]
        [JsonProperty("email")]
        public string? Email { get; set; }
        
    }
}