
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class RemoveMountData
    {

        /// <summary>
        /// Agent details.
        /// </summary>
        [SerializeField]
        [JsonProperty("agent")]
        public AgentJson Agent { get; set; } = default!;
        

        /// <summary>
        /// List of installed mounts after the removal of the selected mount.
        /// </summary>
        [SerializeField]
        [JsonProperty("mounts")]
        public List<ShipMountJson> Mounts { get; set; } = default!;
        

        /// <summary>
        /// Ship cargo details.
        /// </summary>
        [SerializeField]
        [JsonProperty("cargo")]
        public ShipCargoJson Cargo { get; set; } = default!;
        

        /// <summary>
        /// Result of a transaction for a ship modification, such as installing a mount or a module.
        /// </summary>
        [SerializeField]
        [JsonProperty("transaction")]
        public ShipModificationTransactionJson Transaction { get; set; } = default!;
        
    }
}