
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class SellCargoSellCargoRequest
    {

        /// <summary>
        /// The good&apos;s symbol.
        /// </summary>
        [SerializeField]
        [JsonProperty("symbol")]
        public TradeSymbolJson Symbol { get; set; } = default!;
        

        /// <summary>
        /// Amounts of units to sell of the selected good.
        /// </summary>
        [SerializeField]
        [JsonProperty("units")]
        public long Units { get; set; } = default!;
        
    }
}