
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ShipRefineRequestBody
    {

        /// <summary>
        /// The type of good to produce out of the refining process.
        /// </summary>
        [SerializeField]
        [JsonProperty("produce")]
        public Produce Produce { get; set; } = default!;
        
    }
}