
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ShipRefineData
    {

        /// <summary>
        /// Ship cargo details.
        /// </summary>
        [SerializeField]
        [JsonProperty("cargo")]
        public ShipCargoJson Cargo { get; set; } = default!;
        

        /// <summary>
        /// A cooldown is a period of time in which a ship cannot perform certain actions.
        /// </summary>
        [SerializeField]
        [JsonProperty("cooldown")]
        public CooldownJson Cooldown { get; set; } = default!;
        

        /// <summary>
        /// Goods that were produced by this refining process.
        /// </summary>
        [SerializeField]
        [JsonProperty("produced")]
        public List<Produced> Produced { get; set; } = default!;
        

        /// <summary>
        /// Goods that were consumed during this refining process.
        /// </summary>
        [SerializeField]
        [JsonProperty("consumed")]
        public List<Openapi.Models.Requests.Consumed> Consumed { get; set; } = default!;
        
    }
}