
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class Stats
    {

        /// <summary>
        /// Number of registered agents in the game.
        /// </summary>
        [SerializeField]
        [JsonProperty("agents")]
        public long Agents { get; set; } = default!;
        

        /// <summary>
        /// Total number of ships in the game.
        /// </summary>
        [SerializeField]
        [JsonProperty("ships")]
        public long Ships { get; set; } = default!;
        

        /// <summary>
        /// Total number of systems in the game.
        /// </summary>
        [SerializeField]
        [JsonProperty("systems")]
        public long Systems { get; set; } = default!;
        

        /// <summary>
        /// Total number of waypoints in the game.
        /// </summary>
        [SerializeField]
        [JsonProperty("waypoints")]
        public long Waypoints { get; set; } = default!;
        
    }
}