
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class WarpShipData
    {

        /// <summary>
        /// Details of the ship&apos;s fuel tanks including how much fuel was consumed during the last transit or action.
        /// </summary>
        [SerializeField]
        [JsonProperty("fuel")]
        public ShipFuelJson Fuel { get; set; } = default!;
        

        /// <summary>
        /// The navigation information of the ship.
        /// </summary>
        [SerializeField]
        [JsonProperty("nav")]
        public ShipNavJson Nav { get; set; } = default!;
        
    }
}